### PR TITLE
feat(otterdog): add new repos for keyple-api-docs and keyple-actions

### PR DESCRIPTION
**Pull request by jeanpierrefortune**

### CODE REVIEW

**Review by netomi — APPROVED** [review]
LGTM, you can merge yourself with `/otterdog merge`

**Comment by netomi** [comment]
hmm you seem to define to deploy from the main branch, but the github-pages environment only allows to deploy from the gh-pages branch, so there is a conflict that you need to solve for the deployment to work.

**Comment by jeanpierrefortune** [comment]
> hmm you seem to define to deploy from the main branch, but the github-pages environment only allows to deploy from the gh-pages branch, so there is a conflict that you need to solve for the deployment to work.

Thanks for your comment. Indeed, I initially thought that we would only use one branch, but in the end it's not possible with the main branch and it's preferable for managing the repository.
So we have two branches, main and gh-pages.
Do I need to change the otterdog configuration file, or is this not necessary once the repository has been created?

**Pull request merged**
